### ISSUE TITLE
405 error getting SAS token

### ISSUE THREAD

**Issue by Kars130700** [Azure-Samples/azure-typescript-e2e-apps#52]
### This issue is for a: (mark with an `x`)
```
- x bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>13

### Any log messages given by the failure
>Error getting sas token: Request failed with status code 405 AxiosError: Request failed with status code 405 at BL (link)  at XMLHttpRequest.g (link)

### Expected/desired behavior
> get SAS token

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11 Pro
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nm-fg** [comment]
Hi, were you able to fix this issue? I am also having the same problem.
